name: Firebase CI

on: 
  push:
    branches:main


jobs:
  build:
    runs-on:windows-latest
  

  strategy:
    matrix:
      node-version:[16.x]
    steps:
      - uses: actions/checkout@v4
      - name: use Node.js version ${{ matrix.node-version }}
         uses: actions/setup-node@v4
         with:
          node-version: ${{ matrix.node-version }}

     - run: npm i
     - run: npm install -g firebase-tools
     - run: npm run test
     - run: npm run build
     - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
      name: build
      path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


